# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Test against Node.js LTS versions that align with your engine requirements
      # '18.x' covers Node.js 18 LTS
      # '20.x' covers Node.js 20 LTS
      matrix:
        node-version: ['18.x', '20.x'] # Updated to test against LTS versions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies
        # 'npm ci' is preferred in CI environments for clean and consistent installs
        run: npm ci

      - name: Build TypeScript declarations
        # Ensures that your TypeScript declaration files are correctly generated
        run: npm run build:types

      - name: Run tests
        # Executes your test suite, including coverage
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5 # Updated to v5
        with:
          # A token is usually not needed for public repositories,
          # but for private repos, you'd set it up as a GitHub secret:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # Path to your coverage report. Jest usually outputs to 'coverage/lcov.info'
          # Adjust this if your coverage tool outputs to a different path.
          file: ./coverage/lcov.info
          fail_ci_if_error: true # Fail the CI pipeline if Codecov upload fails
          verbose: true # Enable verbose logging for debugging
